spring:
  profiles:
    active: git, vault
  application:
    name: configserver
  cloud:
    config:
      server:
        #native:
          #searchLocations: file:///config/config-repo
        git:
          uri: https://github.com/sovietspy2/spring-cloud-config-repo-test.git
          clone-on-start: true
          default-label: main
        vault:
          port: 8200
          host: 127.0.0.1

server:
  port: 8888

